Nodes:
  "tianji.internal.deepwisdomai.com:6600": 1
Type: 2
APIs:
  - Methods:
      - POST
    Name: 创建项目
    UrlPattern: /sdksvr/createproj
    Plugins:
      rewrite:
        UrlRewrite: /projects
  - Methods:
      - POST
    Name: 获取服务列表
    UrlPattern: /sdksvr/svrlist
    Plugins:
      rewrite:
        UrlRewrite: /projects/service
  - Methods:
      - GET
    Name: 获取数据集列表
    UrlPattern: /sdksvr/datasetlist
    Plugins:
      rewrite:
        UrlRewrite: /datawarehouse/datasets
  - Methods:
      - POST
    Name: 训练项目
    UrlPattern: /sdksvr/projtrain
    Plugins:
      rewrite:
        UrlRewrite: /project/train
  - Methods:
      - POST
    Name: 重新训练项目
    UrlPattern: /sdksvr/projretrain
    Plugins:
      rewrite:
        UrlRewrite: /project/train
  - Methods:
      - POST
    Name: 获取项目信息
    UrlPattern: /sdksvr/projinfo
    Plugins:
      rewrite:
        UrlRewrite: /project
  - Methods:
      - GET
    Name: 获取训练结果
    UrlPattern: /sdksvr/trainresult
    Plugins:
      rewrite:
        UrlRewrite: /project/trial/scheme
  - Methods:
      - POST
    Name: 项目评估
    UrlPattern: /sdksvr/projeval
    Plugins:
      rewrite:
        UrlRewrite: /project/eval
  - Methods:
      - GET
    Name: 获取预测详情
    UrlPattern: /sdksvr/projeval/detail
    Plugins:
      rewrite:
        UrlRewrite: /project/eval
  - Methods:
      - POST
    Name: 发起预测
    UrlPattern: /sdksvr/projeval/predict
    Plugins:
      rewrite:
        UrlRewrite: /project/eval
  - Methods:
      - GET
    Name: 获取预测列表
    UrlPattern: /sdksvr/projeval/list
    Plugins:
      rewrite:
        UrlRewrite: /project/evals
  - Methods:
      - DELETE
    Name: 删除预测
    UrlPattern: /sdksvr/projeval/delete
    Plugins:
      rewrite:
        UrlRewrite: /project/eval
  - Methods:
      - GET
    Name: 离线预测数据集下载
    UrlPattern: /sdksvr/projeval/dataset_download
    Plugins:
      rewrite:
        UrlRewrite: /project/eval/download
  - Methods:
      - GET
    Name: 项目预测报告下载
    UrlPattern: /sdksvr/projeval/result_download
    Plugins:
      rewrite:
        UrlRewrite: /project/eval/zip/download
  - Methods:
      - POST
    Name: 创建推理服务
    UrlPattern: /sdksvr/infersvr
    Plugins:
      rewrite:
        UrlRewrite: /project/infer
  - Methods:
      - POST
    Name: 推理服务启停
    UrlPattern: /sdksvr/svropt
    Plugins:
      rewrite:
        UrlRewrite: /project/service/operation
  - Methods:
      - POST
    Name: 更新项目高级设计
    UrlPattern: /sdksvr/projadvancesetting
    Plugins:
      rewrite:
        UrlRewrite: /project/advance_settings
  - Methods:
      - POST
    Name: 获取模型信息
    UrlPattern: /sdksvr/trainmodelinfo
    Plugins:
      rewrite:
        UrlRewrite: /project/model/select
  - Methods:
      - POST
    Name: 准备数据集
    UrlPattern: /sdksvr/datasetprepare
    Plugins:
      rewrite:
        UrlRewrite: /dataset/prepare
  - Methods:
      - POST
    Name: 上传数据集文件
    UrlPattern: /sdksvr/fileupload
    Plugins:
      rewrite:
        UrlRewrite: /file/upload
  - Methods:
      - POST
    Name: 更新数据集文件
    UrlPattern: /sdksvr/datasetupload
    Plugins:
      rewrite:
        UrlRewrite: /dataset/upload
  - Methods:
      - GET
    Name: 获取数据集详情
    UrlPattern: /sdksvr/datasetinfo
    Plugins:
      rewrite:
        UrlRewrite: /datawarehouse/dataset/info
  - Methods:
      - POST
    Name: 创建推理服务
    UrlPattern: /sdksvr/deploy/create
    Plugins:
      rewrite:
        UrlRewrite: /project/infer
  - Methods:
      - GET
    Name: 获取服务详情
    UrlPattern: /sdksvr/deploy/detail
    Plugins:
      rewrite:
        UrlRewrite: /services/info
  - Methods:
      - GET
    Name: 获取服务部署列表
    UrlPattern: /sdksvr/deploy/list
    Plugins:
      rewrite:
        UrlRewrite: /project/services
  - Methods:
      - POST
    Name: 切换服务常驻状态
    UrlPattern: /sdksvr/deploy/resident
    Plugins:
      rewrite:
        UrlRewrite: /project/service/operation
  - Methods:
      - DELETE
    Name: 删除服务
    UrlPattern: /sdksvr/deploy/delete
    Plugins:
      rewrite:
        UrlRewrite: /project/infer
  - Methods:
      - PATCH
    Name: 重命名服务
    UrlPattern: /sdksvr/deploy/rename
    Plugins:
      rewrite:
        UrlRewrite: /project/infer
  - Methods:
      - GET
    Name: 获取服务日志
    UrlPattern: /sdksvr/deploy/logs
    Plugins:
      rewrite:
        UrlRewrite: /project/service/logs
  - Methods:
      - Get
    Name: 获取服务调用api
    UrlPattern: /sdksvr/deploy/get_api
    Plugins:
      rewrite:
        UrlRewrite: /project/service/api
