Nodes:
  "tianji.internal.deepwisdomai.com:6600": 1
# ServiceAuthFilter: jwt
Type: 2
LimitFilter:
  Rate: 100 #每秒生成几个令牌
  Burst: 1000 #令牌桶最大值
TokenWhiteList:
  URIs:
    - /metrics
Rewrites:
  - Methods:
      - POST
    Desc: 创建项目
    Source: /sdksvr/createproj
    Target: /projects

  - Methods:
      - POST
    Desc: 获取服务列表
    Source: /sdksvr/svrlist
    Target: /projects/service
  - Methods:
      - GET
    Desc: 获取数据集列表
    Source: /sdksvr/datasetlist
    Target: /datawarehouse/datasets
  - Methods:
      - POST
    Desc: 训练项目
    Source: /sdksvr/projtrain
    Target: /project/train
  - Methods:
      - POST
    Desc: 重新训练项目
    Source: /sdksvr/projretrain
    Target: /project/train
  - Methods:
      - POST
    Desc: 获取项目信息
    Source: /sdksvr/projinfo
    Target: /project
  - Methods:
      - GET
    Desc: 获取训练结果
    Source: /sdksvr/trainresult
    Target: /project/trial/scheme
  - Methods:
      - POST
    Desc: 项目评估
    Source: /sdksvr/projeval
    Target: /project/eval
  - Methods:
      - GET
    Desc: 获取预测详情
    Source: /sdksvr/projeval/detail
    Target: /project/eval
  - Methods:
      - POST
    Desc: 发起预测
    Source: /sdksvr/projeval/predict
    Target: /project/eval
  - Methods:
      - GET
    Desc: 获取预测列表
    Source: /sdksvr/projeval/list
    Target: /project/evals
  - Methods:
      - GET
    Desc: 删除预测
    Source: /sdksvr/projeval/delete
    Target: /project/eval
  - Methods:
    - GET
    Desc: 离线预测数据集下载
    Source: /sdksvr/projeval/dataset_download
    Target: /project/eval/download
  - Methods:
    - GET
    Desc: 项目预测报告下载
    Source: /sdksvr/projeval/result_download
    Target: /project/eval/zip/download
  - Methods:
      - POST
    Desc: 创建推理服务
    Source: /sdksvr/infersvr
    Target: /project/infer
  - Methods:
      - POST
    Desc: 推理服务启停
    Source: /sdksvr/svropt
    Target: /project/service/operation
  - Methods:
      - POST
    Desc: 更新项目高级设计
    Source: /sdksvr/projadvancesetting
    Target: /project/advance_settings
  - Methods:
      - POST
    Desc: 获取模型信息
    Source: /sdksvr/trainmodelinfo
    Target: /project/model/select
  - Methods:
      - POST
    Desc: 准备数据集
    Source: /sdksvr/datasetprepare
    Target: /dataset/prepare
  - Methods:
      - POST
    Desc: 上传数据集文件
    Source: /sdksvr/fileupload
    Target: /file/upload
  - Methods:
      - POST
    Desc: 更新数据集文件
    Source: /sdksvr/datasetupload
    Target: /dataset/upload
  - Methods:
      - GET
    Desc: 获取数据集详情
    Source: /sdksvr/datasetinfo
    Target: /datawarehouse/dataset/info
  - Methods:
      - POST
    Desc: 创建推理服务
    Source: /sdksvr/deploy/create
    Target: /project/infer
  - Methods:
      - GET
    Desc: 获取服务详情
    Source: /sdksvr/deploy/detail
    Target: /services/info
  - Methods:
      - GET
    Desc: 获取服务部署列表
    Source: /sdksvr/deploy/list
    Target: /project/services
  - Methods:
      - POST
    Desc: 切换服务常驻状态
    Source: /sdksvr/deploy/resident
    Target: /project/service/operation
  - Methods:
      - DELETE
    Desc: 删除服务
    Source: /sdksvr/deploy/delete
    Target: /project/infer
  - Methods:
      - PATCH
    Desc: 重命名服务
    Source: /sdksvr/deploy/rename
    Target: /project/infer

  - Methods:
      - Get
    Desc: 获取服务日志
    Source: /sdksvr/deploy/logs
    Target: /project/service/logs


